config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'
  get 'comments/new'
  get 'comments/edit'
    #- action with a html page
  root 'subs#index'
  #as will do shortcuts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'sub#index', as: to:


  # HTTP Verbs
  # GET -  Index, show, new, edit,  read
  # POST - create                   create
  # PUT/PATCH update              update
  # DELETE - destroy                destroy


    # get '/subs', to: 'subs#index'
  # get '/apple', to: 'subs#index'
  # post 'subs', to: 'subs#create'

  #embedded route
  #not recommended 
#   resources :subs do #parent 
#     resources :topics #child
#       resources :comments
#   end
# end

#recommended 
resources :subs do
  resources :topics
end

resources :topics do
  resources :comments
end


#likes
# resources :comments do
#   resources :likes
# end

# static_pages
#resources :static_pages
# get '/home, to: static_pages#index'
  # resources :subs, only: [:new, :index]
  # resources :subs, execept: [:create, :new]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :topic
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_topic
  before_action :set_comments, only: [:show, :edit, :update, :destroy]

  def index
    @comments = @topic.comments
  end

  def new
    @comment = topic.comments.new
  end

  def create
    @comment = @topic.comments.new(comments_params)
    if comment.save
      redirect_to_ subs_topic_path(@topic.sub, @topic)
    else 
      render.new 
  
  end

  def edit
  end

  def update
    if @comment.update(comments_params)
      redirect_to_ subs_topic_path(@topic.sub, @topic)
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to_ subs_topic_path(@topic.sub, @topic)
  end

  private

    def comments_params
      params.require(:comment).permit(:body) #CHECK IN SCHEMA
    
    
    end

    def set_comment
      @comment = comment.find(params[:id]) #finds the individual comment
    end


    def set_topic
      @topic = topic.find(params[:id])
    end
    
    


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<br />
<%= link_to 'New Comment', new_topic_comment_path(@topic) %>
<ul>
    <% @comments.each do |comment| %>
        <li>
            <% link_to comment.body, topic_comment_path(@topic, comment) %>
        </li>
    <% end %>
</ul>

app/views/comments/new.html.erb
<h1>new Comment</h1>
<%= form_for [@topic, @comment] do |f| %>
    <%= f.label :body%>
    <%= f.text_area :body, required: true %>
    <%= f.submit %>
<%= end %>