config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'
  get 'comments/new'
  get 'comments/edit'
    #- action with a html page
  root 'subs#index'
  #as will do shortcuts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'sub#index', as: to:


  # HTTP Verbs
  # GET -  Index, show, new, edit,  read
  # POST - create                   create
  # PUT/PATCH update              update
  # DELETE - destroy                destroy


    # get '/subs', to: 'subs#index'
  # get '/apple', to: 'subs#index'
  # post 'subs', to: 'subs#create'

  #embedded route
  #not recommended 
#   resources :subs do #parent 
#     resources :topics #child
#       resources :comments
#   end
# end

#recommended 
resources :subs do
  resources :topics
end

resources :topics do
  resources :comments
end


#likes
# resources :comments do
#   resources :likes
# end

# static_pages
#resources :static_pages
# get '/home, to: static_pages#index'
  # resources :subs, only: [:new, :index]
  # resources :subs, execept: [:create, :new]
end

app/models/topic.rb
class Top < ApplicationRecord
  belongs_to :sub
  has_many :comments
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action: :set_sub
  before_action :set_topic, only: [:show, :edit, :update, :destroy]


  def index
    @topics = @sub.topics
  end

  def show
  end

  def new
    @topic = @sub.topics.new #child is plural regardless action 
  end

  def create
    @topic = @sub.topics.new(topic_params)
    if @topic.save #show page of topic
      redirect_to[@sub, @topic]
    else
      render :new
    end
  end


  def edit
  end

  def update
    if @topic.update(topic_params)
    
    else
      render :edit
    end
  end

  def destory
    @topic.destroy 
    redirect_to sub_topics_path

  private
  #topic params - make sure that it pulls the same type {topic: {title: 'kash', body: 'asdf' }}
  def topic_params
  params.require(:topic).permit(:title, :body)
  
  end


  def set_topic
    @topic = Topic.find(params[:id]) #childs id
end

  def set_sub
    @sub = Sub.find(params[:sub_id]) #parent id

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<h1><%= @topic.id ? 'Edit Topic' : 'New Topic' %></h1>
#with partials you cannot really style them the same 
<br />
<% form_for  [@sub, @topic]%>
<%= f.label :title %>
<%= f.text_field :title, required: true%>
<%= f.label :body %>
<%= f.text_area :body, required: true%>
<%= f.submit %>


# variables we defined in our control, always will be parent and child 

<% end %> ''

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<h1><=% @sub.name %> Topics </h1>
<%= link_to 'Create topic' new_sub_topic_path(@sub)  %> #if you need more than one array just seperate by comma
<br />
<ul>
    <% @topics.each do |topic| %>
        <li>
        <%= link_to topic.name, [@sub, topic] %>  # will go to topic show page#
        </li>
    <% end %>
</ul>

app/views/topics/new.html.erb
<h1>Topics#new</h1>
<p>Find me in app/views/topics/new.html.erb</p>

app/views/topics/show.html.erb
<h1>Topics#show</h1>
<p>Find me in app/views/topics/show.html.erb</p>